# Ollama configuration
ollama:
  model: phi3
  base_url: http://localhost:11434/v1

# OpenAGI agent configuration
# agents:
#   - name: WRITER
#     role: SUMMARISING EXPERT
#     goal: Summarize input into presentable points
  #   backstory: Expert in summarizing the given text
  #   capability: llm_task_executor
  #   task: Summarize points to present to healthcare professionals and the general public separately on COVID-19 latest trends
  #   output_consumer_agent:
  #     - EMAILER

  # - name: EMAILER
  #   role: EMAIL CREATOR
  #   goal: Compose the email based on the content
  #   backstory: Good at composing precise emails
  #   capability: llm_task_executor
  #   task: Compose email based on summary to doctors and the general public separately into a file with subject, summary, and details
  #   output_consumer_agent:
  #     - HGI

EXA_NUM_SEARCH_RESULTS: !!int 1 #number of exa search results
MAX_NUMBER_OF_AGENTS: !!int 5 #defaulted for 5 agents
TEMPERATURE: !!float 0.5
